### ISSUE TITLE
API - Get OAuth Token

### ISSUE THREAD

**Issue by LoadingPleaseWait** [nith822/RazettoStone#2]
- Check that the OAuth token is valid and accept the OAuth token.
- Call verify() from auth.js in create/update API requests
- Update verify() to look for OAuthId in DB before calling Google
- Update API to read from cookie (use below code)
```
req.headers.cookie.split(';').forEach(function (cookie) {
        var temp = cookie.trim().split("=");
        if (temp[0] == "user_auth")
            var OAuthId = temp[1];
    })
```

**Comment by mattAbe** [comment]
@sxb152930 already implemented this.
